apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment-router"
  namespace: {{ .Release.Namespace }}
  labels:
    app: router # TODO: change here!
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router # TODO: change here!
  template:
    metadata:
      labels:
        app: router # TODO: change here!
    spec:
      serviceAccountName: {{ .Release.Name }}-router-service-account
      containers:
      - name: router-container
        image: apostacyh/lmcache-router:latest
        args: # TODO: update here
          - "--service-discovery"
          - "k8s"
          - "--k8s-label-selector"
          - "release=test"
          - "--routing-logic"
          - "session"
          - "--session-key"
          - "x-user-id"
        resources: # TODO: update here
          requests:
            cpu: "4"
            memory: "16G"

