{{- if .Values.servingEngineSpec.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Release.Name }}-hpa"
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vllm
  minReplicas: {{ .Values.servingEngineSpec.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.servingEngineSpec.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.servingEngineSpec.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.servingEngineSpec.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.servingEngineSpec.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.servingEngineSpec.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
