servingEngineSpec:
  runtimeClassName: ""
  modelSpec:
  - name: "opt125m"
    repository: "vllm/vllm-openai"
    tag: "latest"
    modelURL: "facebook/opt-125m"

    replicaCount: 1

    requestCPU: 6
    requestMemory: "16Gi"
    requestGPU: 1

    pvcStorage: "10Gi"
    pvcAccessMode:
      - ReadWriteOnce

routerSpec:
  enableRouter: true
  ingress:
    # Builds the ingress resource on the router service
    enabled: true
    className: "alb"

    # AWS ALB annotations to auto-deploy ALB when router ingress is created
    annotations:
      alb.ingress.kubernetes.io/load-balancer-name: "vllm-router-alb"
      alb.ingress.kubernetes.io/ingress.class: "alb"
      alb.ingress.kubernetes.io/target-type: "ip"
      alb.ingress.kubernetes.io/scheme: "internet-facing"
      alb.ingress.kubernetes.io/listen-ports: "{HTTP: 80}"

    # hosts:
    #   - host: router.example.com
    #     paths:
    #       - path: /
    #         pathType: Prefix
